version: "3.9"

services:
  caddy:
    image: caddy:2.7.4-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - $PWD/caddy/Caddyfile:/etc/caddy/Caddyfile
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    develop:
      watch:
        - action: sync
          path: $PWD/server
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: $PWD/server/package.json
    ports:
      - "8080:8080"
    volumes:
      - $PWD/server/db:/db
  app:
    build:
      context: ./app
      dockerfile: local.Dockerfile
    restart: always
    develop:
      watch:
        - action: sync
          path: $PWD/app
          target: /code
          ignore:
            - node_modules/
        - action: rebuild
          path: $PWD/app/package.json
    ports:
      - 3000:3000
    depends_on:
      - server

networks:
  default:
    driver: bridge
